name: Récupère le test du workflow 1 et retourne son résultat
on: 
  workflow_dispatch:

jobs: 
  job1:
    name: Affiche le résultat du test
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le résultat du 1er workflow
        id: run-test
        uses: ./projet-exemple-main/.github/workflows/exercice.yml@main
      - name: echo le resultat du test
        run: echo ${{ steps.run-test.outcome }}